# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Blog personal de Sergio Quijano Rey
email: sergiquijano@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Bienvenido a mi pequeño blog personal! Como puedes ver, sigue en fase de 
  desarrollo, y no tiene muchas cosas interesantes que puedas ver
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://sergioquijanorey.github.io" # the base hostname & protocol for your site
twitter_username: SergiQuijano
github_username:  SergioQuijanoRey

# Build settings
markdown: kramdown

theme: jekyll-theme-cayman