# Description:
#         Blog configuration file
#         If changes are made, jekyll restart is needed
# Author:
#         Sergio Quijano Rey
#         sergiquijano@gmail.com
# Version:
#         v1.0 - 30/03/2019: First documented version
#         v1.1 - 31/03/2019: Default values are added
#         v1.2 - 01/04/2019: Rebuild of the website

# Site settings
#===============================================================================
title: Blog personal de Sergio Quijano Rey
email: sergiquijano@gmail.com
description: >
  Bienvenido a mi pequeño blog personal! Como puedes ver, no hay muchas entradas,
  con el tiempo iré añadiendo información interesante.
baseurl: ""
url: "https://sergioquijanorey.github.io"
twitter_username: SergiQuijano
github_username:  SergioQuijanoRey

# Build settings
#===============================================================================
markdown: kramdown
theme: jekyll-theme-cayman-blog

# Plugins
#===============================================================================
plugins:
  - jekyll-feed

# Default front-matter
#===============================================================================
defaults:
        -
                scope:
                        path: ""
                values:
                        layout: post
                        author: "Sergio Quijano Rey"
