# Description:
#         Blog configuration file
#         If changes are made, jekyll restart is needed
# Author:
#         Sergio Quijano Rey
#         sergiquijano@gmail.com
# Version:
#         v1.0 - 30/03/2019: First documented version

# Site settings
#===============================================================================
title: Blog personal de Sergio Quijano Rey
email: sergiquijano@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Bienvenido a mi pequeño blog personal! Como puedes ver, sigue en fase de 
  desarrollo, y no tiene muchas cosas interesantes que puedas ver
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://sergioquijanorey.github.io"
twitter_username: SergiQuijano
github_username:  SergioQuijanoRey

# Build settings
#===============================================================================
markdown: kramdown
theme: jekyll-theme-cayman
